apiVersion: v1
kind: ConfigMap
metadata:
  name: tca-cm
data:
  KAFKA__GROUP_ID: tca
  KAFKA__INPUT_TOPICS: overmuse-trades,quotes

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tca-deployment
spec:
  selector:
    matchLabels:
      app: tca
  replicas: 1
  template:
    metadata:
      labels:
        app: tca
    spec:
      containers:
      - name: tca
        image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/tca:${IMAGE_TAG}
        envFrom:
        - secretRef:
            name: kafka
        - configMapRef:
            name: tca-cm
        - configMapRef:
            name: kafka-config-map
